---Entry point of the plugins module
require("plugins.colors")
require("plugins.completion")
require("plugins.copilot")
require("plugins.format")
require("plugins.git")
require("plugins.integrations")
require("plugins.movement")
require("plugins.notes")
require("plugins.picker")
require("plugins.statusline")
